### PR TITLE
Another API for layout

### PR DESCRIPTION
**Pull request by TimWhiting**
This uses named effects to get a sort of object oriented api.

### CODE REVIEW

**Comment by complyue** [comment]
I'm rather enlightened, let's explore the potential for effects going OO, looking forward to see how far we can get toward perfect unification of objects and closures ...

> The venerable master Qc Na was walking with his student, Anton.  Hoping to
> prompt the master into a discussion, Anton said "Master, I have heard that
> objects are a very good thing - is this true?"  Qc Na looked pityingly at
> his student and replied, "Foolish pupil - objects are merely a poor man's
> closures."
> 
> Chastised, Anton took his leave from his master and returned to his cell,
> intent on studying closures.  He carefully read the entire "Lambda: The
> Ultimate..." series of papers and its cousins, and implemented a small
> Scheme interpreter with a closure-based object system.  He learned much, and
> looked forward to informing his master of his progress.
> 
> On his next walk with Qc Na, Anton attempted to impress his master by
> saying "Master, I have diligently studied the matter, and now understand
> that objects are truly a poor man's closures."  Qc Na responded by hitting
> Anton with his stick, saying "When will you learn? Closures are a poor man's
> object."  At that moment, Anton became enlightened.

From: http://people.csail.mit.edu/gregs/ll1-discuss-archive-html/msg03277.html

---

Off the top of my head, maybe "scoped effect" shall be leveraged too, in case mutable states need to be safely managed? e.g.

```koka
fun defaultpage() : ev<html-layout<<pure|e>>>
  with layout <- named handler
    fun set-body-begin-scripts(b)
      ()
    fun set-body-end-scripts(e)
      ()
    fun set-body-content(c)
      ()
    fun set-page-title(t)
      ()
    fun page-title()
      "Default Page"
    fun body-content()
      fn(){}
    fun body-begin-scripts()
      fn(){}
    fun body-end-scripts()
      fn(){}
  layout
```

This implementation is stateless so safe on its own right, but once the `set-xxx()` would alternate some state, it looks quite unsafe for the evidence/handle to escape. My gut feeling for "idiomatic" Koka (tho not really confident about it) is to have an `action: ev<html-layout<<pure|e>>> -> <pure|e> ()` arg for lifetime alignment, possibly with extra `h::Heap`  type params added?

---

Also I feel like to polish the super/descendant relationship specification, to happen at user site instead of lib site.

---

btw, what's diff between `forall <e>` and `some<e>`? Haskell seems to provide `forall` for all cases of existential quantification, there are more cases syntactically/semantically distinguished in Koka?

**Comment by TimWhiting** [comment]
Yes, we should likely leverage scoped effect as well, or do something to ensure it doesn't escape it's scope. I think your approach in #5 has better guarantees with that, but still not fully statically guaranteed. Koka implements mutable variables via a reference to a heap allocated ref currently, so mutable variables are safe, and `value` / `fun` clauses are safe, but `ctl` clauses, etc, are not safe in unscoped named handlers.

**Comment by TimWhiting** [comment]
As far as `some<e>` versus `forall<e>`, some creates a unification variable which could stay as a variable, or be instantiated at some point. (i.e. in this example it will depend on the effects at the use sites of the `web-tmpl-basic`). But once it is instantiated it will not change, and you will get errors if it is used at more than one type. Forall adds a unique unification variable that will be instantiated separately for every reference/call to a function. In this case where the thing that I am quantifying is a value instead of a function with arguments / return value that use the quantified type, I'm not sure there is a difference. However `forall<e>` is probably the more appropriate quantifier since the template is intended to be used in multiple places that might not agree on effects.

**Comment by TimWhiting** [comment]
I definitely like #5 or #6 better than this (we really don't need set, and if you don't mind teaching people about named effects for the use-site api, then it is a lot cleaner).

Named effects are very useful. I think it is worth educating people about them, and using them more frequently in APIs.

**Pull request closed without merging**
