### PR TITLE
[WIP] support page templates

### PR DESCRIPTION
**Pull request by complyue**
This is very work-in-progress (I made some mod for it to compile by 3.1.1, a cleaner PR should be drafted after 3.1.2 is released), I created it as a PR only for a better context in asking your help for the way of proper typing here:

https://github.com/complyue/html/blob/cf4dd28f0ab492d28a6ef270aeeb20006d39481f/html/layout.kk#L61-L69

---

Template-using example here: 

https://github.com/complyue/html/blob/cyue-play/examples/front.kk

### CODE REVIEW

**Comment by complyue** [comment]
https://github.com/complyue/html/blob/cca192b0be4cb5a15e98c27d9f813908fb998219/html/layout.kk#L63-L71

```koka
pub alias html-tmpl = <
  page-title,
  body-begin-scripts,
  body-content,
  body-end-scripts
>
```

```koka
/*
effects do not match
  inferred effect: <body-begin-scripts,body-content,body-end-scripts,page-title|$e>
  expected effect: <html-tmpl,html-builder/html-tree|$e>
*/
  create-component
    html
      page-head(page)()
      page-body(page)()

```

Does it seem like a Koka typing bug?

**Comment by TimWhiting** [comment]
I think this gets you what you want?
https://github.com/koka-community/html/tree/cyue-play-fix

I tried just fixing the effect annotation, but ended up having to change some more to actually get it to work.

Part of the issue is that there are a few apis that would require bidirectional effects https://dl.acm.org/doi/abs/10.1145/3428207.

**Comment by complyue** [comment]
Thanks for the info!

But I don't see more commits in `cyue-play-fix` branch atm, maybe you forget to push your local changes?

So is bidirectional effects currently supported by Koka?

**Comment by complyue** [comment]
Please use #2 for further discussion, closing this one.

**Pull request closed without merging**
