### PR TITLE
Html Templating Design #2

### PR DESCRIPTION
**Pull request by TimWhiting**
Some fixes

### CODE REVIEW

**Comment by TimWhiting** [comment]
Also look at #4 for another API design.

**Comment by complyue** [comment]
This perfectly materializes the idea originally in my mind, nice typing all around 👍 

I like this approach overall, except the clumsy `create-component` callback.

After seeing #4, I feel rather enlightened, and would very like to explore the potential for effects going OO, looking forward to see how far we can get toward perfect unification of objects and closures ...

> The venerable master Qc Na was walking with his student, Anton.  Hoping to
> prompt the master into a discussion, Anton said "Master, I have heard that
> objects are a very good thing - is this true?"  Qc Na looked pityingly at
> his student and replied, "Foolish pupil - objects are merely a poor man's
> closures."
> 
> Chastised, Anton took his leave from his master and returned to his cell,
> intent on studying closures.  He carefully read the entire "Lambda: The
> Ultimate..." series of papers and its cousins, and implemented a small
> Scheme interpreter with a closure-based object system.  He learned much, and
> looked forward to informing his master of his progress.
> 
> On his next walk with Qc Na, Anton attempted to impress his master by
> saying "Master, I have diligently studied the matter, and now understand
> that objects are truly a poor man's closures."  Qc Na responded by hitting
> Anton with his stick, saying "When will you learn? Closures are a poor man's
> object."  At that moment, Anton became enlightened.

From: http://people.csail.mit.edu/gregs/ll1-discuss-archive-html/msg03277.html

---

btw, am I understanding it correctly that `override` as in `with override fun body-end-scripts()`  works like subsequent statements have the overridden effect masked?

**Comment by TimWhiting** [comment]
Override semantics are a bit different than what you specifically stated, but probably what you had in mind.
Further statements will not see both handlers in their scope, and cannot mask to get the original version.
They only see the override.
So it is slightly different than `mask<effect>` which would hide the closest version to the use site (the override). 
Instead it uses `mask behind<effect>`, which removes a duplicate handler from the evidence but not the most recently installed handler, instead the one 'behind' it.

**Comment by TimWhiting** [comment]
I'll close this one, since I think we'll probably go with something closer to #6.

**Pull request closed without merging**
